name: Codacy Security Scan

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  codacy-security-scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write   # to upload SARIF
      contents: read
    steps:
      - uses: actions/checkout@v4

      # Run Codacy CLI and emit SARIF (don’t fail the job; let GH handle policy)
      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
        with:
          output: results.sarif
          format: sarif
          gh-code-scanning-compat: true
          max-allowed-issues: 2147483647   # don’t block SARIF creation

      # Upload SARIF to GitHub Code Scanning
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
